In [1]:
import pandas as pd

df= pd.read_csv('../ml_training.csv')
df.head()

,source,level,confidence,classified_by,clean_message,raw_message
0,hdfs,INFO,0.0,Unclassified,PacketResponder 1 for block <BLK> terminating,PacketResponder 1 for block blk_38865049064139...
1,hdfs,INFO,0.0,Unclassified,PacketResponder 0 for block <BLK> terminating,PacketResponder 0 for block blk_-6952295868487...
2,hdfs,INFO,0.0,Unclassified,PacketResponder 2 for block <BLK> terminating,PacketResponder 2 for block blk_82291938032499...
3,hdfs,INFO,0.0,Unclassified,PacketResponder 2 for block <BLK> terminating,PacketResponder 2 for block blk_-6670958622368...
4,hdfs,INFO,0.0,Unclassified,PacketResponder 2 for block <BLK> terminating,PacketResponder 2 for block blk_57249283928729...

In [2]:
df.level.value_counts()

level
INFO        3955
CRITICAL     349
WARNING      121
ERROR         61
Name: count, dtype: int64

In [ ]:
df=pd.read_csv('../synthetic_logs.csv')

In [4]:
df.head()

,source,level,confidence,classified_by,clean_message,raw_message
0,hdfs,INFO,0.0,Synthetic,Received block blk_-622746488039229241 of size...,Received block blk_-622746488039229241 of size...
1,bgl,INFO,0.0,Synthetic,shutdown complete,shutdown complete
2,thunderbird,INFO,0.0,Synthetic,Now running on #29#'s privileges.,Now running on #29#'s privileges.
3,hadoop,INFO,0.0,Synthetic,Adding job token for job_1445144423722_0829_m_...,Adding job token for job_1445144423722_0829_m_...
4,hdfs,INFO,0.0,Synthetic,Verification succeeded for blk_-96684074210205...,Verification succeeded for blk_-96684074210205...

In [5]:
df.level.value_counts()

level
CRITICAL    6651
INFO        3045
WARNING      441
Name: count, dtype: int64

In [7]:
df=pd.read_csv('../data/synthetic_logs.csv')

In [8]:
df.head()

,source,level,confidence,classified_by,clean_message,raw_message
0,hdfs,INFO,0.0,Synthetic,Received block blk_-622746488039229241 of size...,Received block blk_-622746488039229241 of size...
1,bgl,INFO,0.0,Synthetic,shutdown complete,shutdown complete
2,thunderbird,INFO,0.0,Synthetic,Now running on #29#'s privileges.,Now running on #29#'s privileges.
3,hadoop,INFO,0.0,Synthetic,Adding job token for job_1445144423722_0829_m_...,Adding job token for job_1445144423722_0829_m_...
4,hdfs,INFO,0.0,Synthetic,Verification succeeded for blk_-96684074210205...,Verification succeeded for blk_-96684074210205...

In [9]:
df.level.value_counts()

level
ERROR       6939
WARNING     6879
CRITICAL    6651
INFO        3045
Name: count, dtype: int64

In [10]:
df_original = pd.read_csv('../data/ml_training.csv')
df_synth    = pd.read_csv('../data/synthetic_logs.csv')
df_merged   = pd.concat([df_original, df_synth], ignore_index=True)
df_merged.to_csv('../data/merged_logs.csv', index=False)
df_merged['level'].value_counts()
# INFO        7000
# CRITICAL    7000
# WARNING     7000
# ERROR       7000

level
INFO        7000
WARNING     7000
CRITICAL    7000
ERROR       7000
Name: count, dtype: int64